config/routes.rb
ResourceManager::Application.routes.draw do
  resources :projects

  resources :users
  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/actual_working_times.rb
class ActualWorkingTimes < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  
  # attr_accessible :title, :body
  attr_accessible :user_id, :project_id, :actual_working_date, :actual_manhour
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :actual_working_time
  
  attr_accessible :badget, :project_end_date, :project_name, :project_start_date
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :actual_working_times
  
  attr_accessible :email, :name
end

app/controllers/actual_working_times_controller.rb
class ActualWorkingTimesController < ApplicationController

    # show actual working time on project
    def index
	   @actual_working_times = ActualWorkingTimes.find(:all,
	                                                   :include => [:user, :project],
													   :conditions => ['user_id = :user_id', {:user_id => session[:user].id}],
													   :order => 'actual_working_date ASC')
    end
	
	# report actual working time on project
	def new
	  if params[:id]
 	    @actual_working_time = ActualWorkingTimes.find(params[:id])
      else
 	    @actual_working_time = ActualWorkingTimes.new	    
	  end

      @projects = Project.all
	  @users = User.all

	end
	
	def create
	  params[:actual_working_times][:user_id] = session[:user].id
 	  @actual_working_time = ActualWorkingTimes.new(params[:actual_working_times])
      @actual_working_time.save
	  
	  @actual_working_times = ActualWorkingTimes.find(:all, :include => [:user, :project], :conditions => ['user_id = :user_id', {:user_id => session[:user].id}])
	  render 'index'
	end
	
	def destroy
      @actual_working_time = ActualWorkingTimes.find(:first,
	                                                 :conditions => ['id = :id and user_id = :user_id', {:id => params[:id], :user_id => session[:user].id}])
      
      @actual_working_time.destroy if @actual_working_time
	  @actual_working_times = ActualWorkingTimes.find(:all, :include => [:user, :project], :conditions => ['user_id = :user_id', {:user_id => session[:user].id}])
	  render 'index'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
  
  def login
    user = User.find_by_name(params[:user][:name])
	
	if user
	  session[:user] = user
	  redirect_to :controller => 'actual_working_times'
	else
      render 'index'	
	end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/actual_working_time_helper.rb
module ActualWorkingTimeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actual_working_times/_form.html.erb
<%= form_tag({:action => 'create'}, {:id => 'actual_working_times', :name => 'actual_working_times'}) do |f| %>

  <%= label_tag 'user_id' %>:
  <%= session[:user].name %><br />
  
  <%= label_tag 'project_id' %>:
  <%= select :actual_working_times, :project_id, @projects.map{|project| [project.project_name, project.id]} %><br />
  
  <%= label_tag 'actual_working_date' %>:
  <%= date_select :actual_working_times, :actual_working_date %><br />
  
  <%= label_tag 'actual_manhour' %>:
  <%= number_field_tag 'actual_working_times[actual_manhour]' %><br />

  <%= label_tag '備考' %>:
  <%= text_field_tag 'actual_working_times[actual_working_time_other]' %><br />
  
  <%= submit_tag "report submit" %>
<% end %>

app/views/actual_working_times/index.html.erb
<table>
<% @actual_working_times.each do |actual_working_time| %>
  <tr>
    <td><%= actual_working_time.actual_working_date %></td>
    <td><%= actual_working_time.user_id %></td>
    <td><%= actual_working_time.user.name %></td>	
    <td><%= actual_working_time.project_id %></td>
	<td><%= actual_working_time.project.project_name %></td>
    <td><%= actual_working_time.actual_manhour %></td>
	<td><%= link_to 'delete', :action => 'destroy', :id => actual_working_time.id %></td>
  </tr>
<% end %>

</table>
<%= link_to 'report', :action => 'new' %>

app/views/actual_working_times/new.html.erb
<html>
<body>
<h1>report actual working time</h1>

<%= render 'form' %>

<%= link_to 'Back', :action => 'index' %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResourceManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/index.html.erb
<%= form_tag :action => 'login' do |f| %>
  <%= text_field :user, :name %>
  <%= submit_tag "login" %>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_name %><br />
    <%= f.text_field :project_name %>
  </div>
  <div class="field">
    <%= f.label :badget %><br />
    <%= f.number_field :badget %>
  </div>
  <div class="field">
    <%= f.label :project_start_date %><br />
    <%= f.date_select :project_start_date %>
  </div>
  <div class="field">
    <%= f.label :project_end_date %><br />
    <%= f.date_select :project_end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Project name</th>
    <th>Badget</th>
    <th>Project start date</th>
    <th>Project end date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.project_name %></td>
    <td><%= project.badget %></td>
    <td><%= project.project_start_date %></td>
    <td><%= project.project_end_date %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project name:</b>
  <%= @project.project_name %>
</p>

<p>
  <b>Badget:</b>
  <%= @project.badget %>
</p>

<p>
  <b>Project start date:</b>
  <%= @project.project_start_date %>
</p>

<p>
  <b>Project end date:</b>
  <%= @project.project_end_date %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>